version: '3'

services:
  app:
    build: docker/build
    tty: true
    restart: unless-stopped
    volumes:
      - ./app:/app/
    depends_on:
      - db
    links:
      - db

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/allosite.conf:/etc/nginx/conf.d/allosite.conf
      - ./app:/app/
    depends_on:
      - app
    links:
      - app
    ports:
      - "80:80"

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env/db.env