version: '3'

services:
  app:
    build: docker/build
    tty: true
    restart: unless-stopped
    volumes:
      - ./app:/app/
    depends_on:
      - db
    links:
      - db

  nginx:
    build:
      context: docker/build
      dockerfile: Dockerfile-nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/allosite.conf:/etc/nginx/conf.d/allosite.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
      - ./app:/app/
    depends_on:
      - app
    links:
      - app
    ports:
#      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env/db.env